# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/dispatcher.proto for package 'demo'

require 'grpc'
require 'protos/dispatcher_pb'

module Demo
  module Dispatcher
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'demo.Dispatcher'

      rpc :Ping, PingReq, PingResp
    end

    Stub = Service.rpc_stub_class
  end
end
